/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RootImport } from './routes/root'
import { Route as RootPageImport } from './routes/RootPage'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedJwtdecoderImport } from './routes/_authenticated/jwtdecoder'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as auth500Import } from './routes/(auth)/500'
import { Route as AuthenticatedUserProfileUserIdImport } from './routes/_authenticated/userProfile/$userId'
import { Route as AuthenticatedTestInterfaceTestIdImport } from './routes/_authenticated/testInterface/$testId'
import { Route as AuthenticatedEditTestTestIdImport } from './routes/_authenticated/editTest/$testId'
import { Route as AuthenticatedCollaboratorHistoryUserIdImport } from './routes/_authenticated/collaboratorHistory/$userId'
import { Route as AuthenticatedReportsTestIdCollaboratorIdImport } from './routes/_authenticated/reports/$testId/$collaboratorId'
import { Route as AuthenticatedCalendarRouteOptionsImport } from './routes/_authenticated/calendar/route.options'



// Create Virtual Routes

const errors503LazyImport = createFileRoute('/(errors)/503')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const authSignUpLazyImport = createFileRoute('/(auth)/sign-up')()
const authSignIn2LazyImport = createFileRoute('/(auth)/sign-in-2')()
const authForgotPasswordLazyImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const AuthenticatedSettingsRouteLazyImport = createFileRoute(
  '/_authenticated/settings',
)()
const AuthenticatedUsersIndexLazyImport = createFileRoute(
  '/_authenticated/users/',
)()
const AuthenticatedTestsIndexLazyImport = createFileRoute(
  '/_authenticated/tests/',
)()
const AuthenticatedTestHistoryIndexLazyImport = createFileRoute(
  '/_authenticated/testHistory/',
)()
const AuthenticatedTasksIndexLazyImport = createFileRoute(
  '/_authenticated/tasks/',
)()
const AuthenticatedSettingsIndexLazyImport = createFileRoute(
  '/_authenticated/settings/',
)()
const AuthenticatedPinboardIndexLazyImport = createFileRoute(
  '/_authenticated/pinboard/',
)()
const AuthenticatedHelpCenterIndexLazyImport = createFileRoute(
  '/_authenticated/help-center/',
)()
const AuthenticatedDashboardManagerIndexLazyImport = createFileRoute(
  '/_authenticated/dashboard-manager/',
)()
const AuthenticatedCreateTestsIndexLazyImport = createFileRoute(
  '/_authenticated/createTests/',
)()
const AuthenticatedChatsIndexLazyImport = createFileRoute(
  '/_authenticated/chats/',
)()
const AuthenticatedChallengesIndexLazyImport = createFileRoute(
  '/_authenticated/challenges/',
)()
const AuthenticatedCalendarIndexLazyImport = createFileRoute(
  '/_authenticated/calendar/',
)()
const AuthenticatedAppsIndexLazyImport = createFileRoute(
  '/_authenticated/apps/',
)()
const AuthenticatedSettingsNotificationsLazyImport = createFileRoute(
  '/_authenticated/settings/notifications',
)()
const AuthenticatedSettingsDisplayLazyImport = createFileRoute(
  '/_authenticated/settings/display',
)()
const AuthenticatedSettingsAppearanceLazyImport = createFileRoute(
  '/_authenticated/settings/appearance',
)()
const AuthenticatedSettingsAccountLazyImport = createFileRoute(
  '/_authenticated/settings/account',
)()
const AuthenticatedCoursesCourseIdIndexLazyImport = createFileRoute(
  '/_authenticated/courses/$courseId/',
)()
const AuthenticatedCoursesCourseIdLevelsLevelIdLazyImport = createFileRoute(
  '/_authenticated/courses/$courseId/levels/$levelId',
)()

// Create/Update Routes

const RootRoute = RootImport.update({
  id: '/root',
  path: '/root',
  getParentRoute: () => rootRoute,
} as any)

const RootPageRoute = RootPageImport.update({
  id: '/RootPage',
  path: '/RootPage',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const errors503LazyRoute = errors503LazyImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const authSignUpLazyRoute = authSignUpLazyImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))

const authSignIn2LazyRoute = authSignIn2LazyImport
  .update({
    id: '/(auth)/sign-in-2',
    path: '/sign-in-2',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-in-2.lazy').then((d) => d.Route))

const authForgotPasswordLazyRoute = authForgotPasswordLazyImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsRouteLazyRoute =
  AuthenticatedSettingsRouteLazyImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/route.lazy').then((d) => d.Route),
  )

const AuthenticatedJwtdecoderRoute = AuthenticatedJwtdecoderImport.update({
  id: '/jwtdecoder',
  path: '/jwtdecoder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const auth500Route = auth500Import.update({
  id: '/(auth)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedUsersIndexLazyRoute =
  AuthenticatedUsersIndexLazyImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/users/index.lazy').then((d) => d.Route),
  )

const AuthenticatedTestsIndexLazyRoute =
  AuthenticatedTestsIndexLazyImport.update({
    id: '/tests/',
    path: '/tests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/tests/index.lazy').then((d) => d.Route),
  )

const AuthenticatedTestHistoryIndexLazyRoute =
  AuthenticatedTestHistoryIndexLazyImport.update({
    id: '/testHistory/',
    path: '/testHistory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/testHistory/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedTasksIndexLazyRoute =
  AuthenticatedTasksIndexLazyImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/tasks/index.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsIndexLazyRoute =
  AuthenticatedSettingsIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/index.lazy').then((d) => d.Route),
  )

const AuthenticatedPinboardIndexLazyRoute =
  AuthenticatedPinboardIndexLazyImport.update({
    id: '/pinboard/',
    path: '/pinboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/pinboard/index.lazy').then((d) => d.Route),
  )

const AuthenticatedHelpCenterIndexLazyRoute =
  AuthenticatedHelpCenterIndexLazyImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/help-center/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDashboardManagerIndexLazyRoute =
  AuthenticatedDashboardManagerIndexLazyImport.update({
    id: '/dashboard-manager/',
    path: '/dashboard-manager/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard-manager/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedCreateTestsIndexLazyRoute =
  AuthenticatedCreateTestsIndexLazyImport.update({
    id: '/createTests/',
    path: '/createTests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/createTests/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedChatsIndexLazyRoute =
  AuthenticatedChatsIndexLazyImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/chats/index.lazy').then((d) => d.Route),
  )

const AuthenticatedChallengesIndexLazyRoute =
  AuthenticatedChallengesIndexLazyImport.update({
    id: '/challenges/',
    path: '/challenges/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/challenges/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedCalendarIndexLazyRoute =
  AuthenticatedCalendarIndexLazyImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/calendar/index.lazy').then((d) => d.Route),
  )

const AuthenticatedAppsIndexLazyRoute = AuthenticatedAppsIndexLazyImport.update(
  {
    id: '/apps/',
    path: '/apps/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/apps/index.lazy').then((d) => d.Route),
)

const AuthenticatedSettingsNotificationsLazyRoute =
  AuthenticatedSettingsNotificationsLazyImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/notifications.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsDisplayLazyRoute =
  AuthenticatedSettingsDisplayLazyImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/display.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAppearanceLazyRoute =
  AuthenticatedSettingsAppearanceLazyImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/appearance.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAccountLazyRoute =
  AuthenticatedSettingsAccountLazyImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/account.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedUserProfileUserIdRoute =
  AuthenticatedUserProfileUserIdImport.update({
    id: '/userProfile/$userId',
    path: '/userProfile/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedTestInterfaceTestIdRoute =
  AuthenticatedTestInterfaceTestIdImport.update({
    id: '/testInterface/$testId',
    path: '/testInterface/$testId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedEditTestTestIdRoute =
  AuthenticatedEditTestTestIdImport.update({
    id: '/editTest/$testId',
    path: '/editTest/$testId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCollaboratorHistoryUserIdRoute =
  AuthenticatedCollaboratorHistoryUserIdImport.update({
    id: '/collaboratorHistory/$userId',
    path: '/collaboratorHistory/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCoursesCourseIdIndexLazyRoute =
  AuthenticatedCoursesCourseIdIndexLazyImport.update({
    id: '/courses/$courseId/',
    path: '/courses/$courseId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/courses/$courseId/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedReportsTestIdCollaboratorIdRoute =
  AuthenticatedReportsTestIdCollaboratorIdImport.update({
    id: '/reports/$testId/$collaboratorId',
    path: '/reports/$testId/$collaboratorId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCalendarRouteOptionsRoute =
  AuthenticatedCalendarRouteOptionsImport.update({
    id: '/calendar/route/options',
    path: '/calendar/route/options',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCoursesCourseIdLevelsLevelIdLazyRoute =
  AuthenticatedCoursesCourseIdLevelsLevelIdLazyImport.update({
    id: '/courses/$courseId/levels/$levelId',
    path: '/courses/$courseId/levels/$levelId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/courses/$courseId/levels/$levelId.lazy'
    ).then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/RootPage': {
      id: '/RootPage'
      path: '/RootPage'
      fullPath: '/RootPage'
      preLoaderRoute: typeof RootPageImport
      parentRoute: typeof rootRoute
    }
    '/root': {
      id: '/root'
      path: '/root'
      fullPath: '/root'
      preLoaderRoute: typeof RootImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/500': {
      id: '/(auth)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof auth500Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/jwtdecoder': {
      id: '/_authenticated/jwtdecoder'
      path: '/jwtdecoder'
      fullPath: '/jwtdecoder'
      preLoaderRoute: typeof AuthenticatedJwtdecoderImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2LazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/collaboratorHistory/$userId': {
      id: '/_authenticated/collaboratorHistory/$userId'
      path: '/collaboratorHistory/$userId'
      fullPath: '/collaboratorHistory/$userId'
      preLoaderRoute: typeof AuthenticatedCollaboratorHistoryUserIdImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/editTest/$testId': {
      id: '/_authenticated/editTest/$testId'
      path: '/editTest/$testId'
      fullPath: '/editTest/$testId'
      preLoaderRoute: typeof AuthenticatedEditTestTestIdImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/testInterface/$testId': {
      id: '/_authenticated/testInterface/$testId'
      path: '/testInterface/$testId'
      fullPath: '/testInterface/$testId'
      preLoaderRoute: typeof AuthenticatedTestInterfaceTestIdImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/userProfile/$userId': {
      id: '/_authenticated/userProfile/$userId'
      path: '/userProfile/$userId'
      fullPath: '/userProfile/$userId'
      preLoaderRoute: typeof AuthenticatedUserProfileUserIdImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/calendar/': {
      id: '/_authenticated/calendar/'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/challenges/': {
      id: '/_authenticated/challenges/'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/createTests/': {
      id: '/_authenticated/createTests/'
      path: '/createTests'
      fullPath: '/createTests'
      preLoaderRoute: typeof AuthenticatedCreateTestsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/dashboard-manager/': {
      id: '/_authenticated/dashboard-manager/'
      path: '/dashboard-manager'
      fullPath: '/dashboard-manager'
      preLoaderRoute: typeof AuthenticatedDashboardManagerIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/pinboard/': {
      id: '/_authenticated/pinboard/'
      path: '/pinboard'
      fullPath: '/pinboard'
      preLoaderRoute: typeof AuthenticatedPinboardIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/testHistory/': {
      id: '/_authenticated/testHistory/'
      path: '/testHistory'
      fullPath: '/testHistory'
      preLoaderRoute: typeof AuthenticatedTestHistoryIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/tests/': {
      id: '/_authenticated/tests/'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof AuthenticatedTestsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/calendar/route/options': {
      id: '/_authenticated/calendar/route/options'
      path: '/calendar/route/options'
      fullPath: '/calendar/route/options'
      preLoaderRoute: typeof AuthenticatedCalendarRouteOptionsImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/reports/$testId/$collaboratorId': {
      id: '/_authenticated/reports/$testId/$collaboratorId'
      path: '/reports/$testId/$collaboratorId'
      fullPath: '/reports/$testId/$collaboratorId'
      preLoaderRoute: typeof AuthenticatedReportsTestIdCollaboratorIdImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/courses/$courseId/': {
      id: '/_authenticated/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/courses/$courseId/levels/$levelId': {
      id: '/_authenticated/courses/$courseId/levels/$levelId'
      path: '/courses/$courseId/levels/$levelId'
      fullPath: '/courses/$courseId/levels/$levelId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdLevelsLevelIdLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedSettingsRouteLazyRouteChildren {
  AuthenticatedSettingsAccountLazyRoute: typeof AuthenticatedSettingsAccountLazyRoute
  AuthenticatedSettingsAppearanceLazyRoute: typeof AuthenticatedSettingsAppearanceLazyRoute
  AuthenticatedSettingsDisplayLazyRoute: typeof AuthenticatedSettingsDisplayLazyRoute
  AuthenticatedSettingsNotificationsLazyRoute: typeof AuthenticatedSettingsNotificationsLazyRoute
  AuthenticatedSettingsIndexLazyRoute: typeof AuthenticatedSettingsIndexLazyRoute
}

const AuthenticatedSettingsRouteLazyRouteChildren: AuthenticatedSettingsRouteLazyRouteChildren =
  {
    AuthenticatedSettingsAccountLazyRoute:
      AuthenticatedSettingsAccountLazyRoute,
    AuthenticatedSettingsAppearanceLazyRoute:
      AuthenticatedSettingsAppearanceLazyRoute,
    AuthenticatedSettingsDisplayLazyRoute:
      AuthenticatedSettingsDisplayLazyRoute,
    AuthenticatedSettingsNotificationsLazyRoute:
      AuthenticatedSettingsNotificationsLazyRoute,
    AuthenticatedSettingsIndexLazyRoute: AuthenticatedSettingsIndexLazyRoute,
  }

const AuthenticatedSettingsRouteLazyRouteWithChildren =
  AuthenticatedSettingsRouteLazyRoute._addFileChildren(
    AuthenticatedSettingsRouteLazyRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedJwtdecoderRoute: typeof AuthenticatedJwtdecoderRoute
  AuthenticatedSettingsRouteLazyRoute: typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCollaboratorHistoryUserIdRoute: typeof AuthenticatedCollaboratorHistoryUserIdRoute
  AuthenticatedEditTestTestIdRoute: typeof AuthenticatedEditTestTestIdRoute
  AuthenticatedTestInterfaceTestIdRoute: typeof AuthenticatedTestInterfaceTestIdRoute
  AuthenticatedUserProfileUserIdRoute: typeof AuthenticatedUserProfileUserIdRoute
  AuthenticatedAppsIndexLazyRoute: typeof AuthenticatedAppsIndexLazyRoute
  AuthenticatedCalendarIndexLazyRoute: typeof AuthenticatedCalendarIndexLazyRoute
  AuthenticatedChallengesIndexLazyRoute: typeof AuthenticatedChallengesIndexLazyRoute
  AuthenticatedChatsIndexLazyRoute: typeof AuthenticatedChatsIndexLazyRoute
  AuthenticatedCreateTestsIndexLazyRoute: typeof AuthenticatedCreateTestsIndexLazyRoute
  AuthenticatedDashboardManagerIndexLazyRoute: typeof AuthenticatedDashboardManagerIndexLazyRoute
  AuthenticatedHelpCenterIndexLazyRoute: typeof AuthenticatedHelpCenterIndexLazyRoute
  AuthenticatedPinboardIndexLazyRoute: typeof AuthenticatedPinboardIndexLazyRoute
  AuthenticatedTasksIndexLazyRoute: typeof AuthenticatedTasksIndexLazyRoute
  AuthenticatedTestHistoryIndexLazyRoute: typeof AuthenticatedTestHistoryIndexLazyRoute
  AuthenticatedTestsIndexLazyRoute: typeof AuthenticatedTestsIndexLazyRoute
  AuthenticatedUsersIndexLazyRoute: typeof AuthenticatedUsersIndexLazyRoute
  AuthenticatedCalendarRouteOptionsRoute: typeof AuthenticatedCalendarRouteOptionsRoute
  AuthenticatedReportsTestIdCollaboratorIdRoute: typeof AuthenticatedReportsTestIdCollaboratorIdRoute
  AuthenticatedCoursesCourseIdIndexLazyRoute: typeof AuthenticatedCoursesCourseIdIndexLazyRoute
  AuthenticatedCoursesCourseIdLevelsLevelIdLazyRoute: typeof AuthenticatedCoursesCourseIdLevelsLevelIdLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedJwtdecoderRoute: AuthenticatedJwtdecoderRoute,
  AuthenticatedSettingsRouteLazyRoute:
    AuthenticatedSettingsRouteLazyRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCollaboratorHistoryUserIdRoute:
    AuthenticatedCollaboratorHistoryUserIdRoute,
  AuthenticatedEditTestTestIdRoute: AuthenticatedEditTestTestIdRoute,
  AuthenticatedTestInterfaceTestIdRoute: AuthenticatedTestInterfaceTestIdRoute,
  AuthenticatedUserProfileUserIdRoute: AuthenticatedUserProfileUserIdRoute,
  AuthenticatedAppsIndexLazyRoute: AuthenticatedAppsIndexLazyRoute,
  AuthenticatedCalendarIndexLazyRoute: AuthenticatedCalendarIndexLazyRoute,
  AuthenticatedChallengesIndexLazyRoute: AuthenticatedChallengesIndexLazyRoute,
  AuthenticatedChatsIndexLazyRoute: AuthenticatedChatsIndexLazyRoute,
  AuthenticatedCreateTestsIndexLazyRoute:
    AuthenticatedCreateTestsIndexLazyRoute,
  AuthenticatedDashboardManagerIndexLazyRoute:
    AuthenticatedDashboardManagerIndexLazyRoute,
  AuthenticatedHelpCenterIndexLazyRoute: AuthenticatedHelpCenterIndexLazyRoute,
  AuthenticatedPinboardIndexLazyRoute: AuthenticatedPinboardIndexLazyRoute,
  AuthenticatedTasksIndexLazyRoute: AuthenticatedTasksIndexLazyRoute,
  AuthenticatedTestHistoryIndexLazyRoute:
    AuthenticatedTestHistoryIndexLazyRoute,
  AuthenticatedTestsIndexLazyRoute: AuthenticatedTestsIndexLazyRoute,
  AuthenticatedUsersIndexLazyRoute: AuthenticatedUsersIndexLazyRoute,
  AuthenticatedCalendarRouteOptionsRoute:
    AuthenticatedCalendarRouteOptionsRoute,
  AuthenticatedReportsTestIdCollaboratorIdRoute:
    AuthenticatedReportsTestIdCollaboratorIdRoute,
  AuthenticatedCoursesCourseIdIndexLazyRoute:
    AuthenticatedCoursesCourseIdIndexLazyRoute,
  AuthenticatedCoursesCourseIdLevelsLevelIdLazyRoute:
    AuthenticatedCoursesCourseIdLevelsLevelIdLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/RootPage': typeof RootPageRoute
  '/root': typeof RootRoute
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/jwtdecoder': typeof AuthenticatedJwtdecoderRoute
  '/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/collaboratorHistory/$userId': typeof AuthenticatedCollaboratorHistoryUserIdRoute
  '/editTest/$testId': typeof AuthenticatedEditTestTestIdRoute
  '/testInterface/$testId': typeof AuthenticatedTestInterfaceTestIdRoute
  '/userProfile/$userId': typeof AuthenticatedUserProfileUserIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/apps': typeof AuthenticatedAppsIndexLazyRoute
  '/calendar': typeof AuthenticatedCalendarIndexLazyRoute
  '/challenges': typeof AuthenticatedChallengesIndexLazyRoute
  '/chats': typeof AuthenticatedChatsIndexLazyRoute
  '/createTests': typeof AuthenticatedCreateTestsIndexLazyRoute
  '/dashboard-manager': typeof AuthenticatedDashboardManagerIndexLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/pinboard': typeof AuthenticatedPinboardIndexLazyRoute
  '/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/tasks': typeof AuthenticatedTasksIndexLazyRoute
  '/testHistory': typeof AuthenticatedTestHistoryIndexLazyRoute
  '/tests': typeof AuthenticatedTestsIndexLazyRoute
  '/users': typeof AuthenticatedUsersIndexLazyRoute
  '/calendar/route/options': typeof AuthenticatedCalendarRouteOptionsRoute
  '/reports/$testId/$collaboratorId': typeof AuthenticatedReportsTestIdCollaboratorIdRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdIndexLazyRoute
  '/courses/$courseId/levels/$levelId': typeof AuthenticatedCoursesCourseIdLevelsLevelIdLazyRoute
}

export interface FileRoutesByTo {
  '/RootPage': typeof RootPageRoute
  '/root': typeof RootRoute
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/jwtdecoder': typeof AuthenticatedJwtdecoderRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/collaboratorHistory/$userId': typeof AuthenticatedCollaboratorHistoryUserIdRoute
  '/editTest/$testId': typeof AuthenticatedEditTestTestIdRoute
  '/testInterface/$testId': typeof AuthenticatedTestInterfaceTestIdRoute
  '/userProfile/$userId': typeof AuthenticatedUserProfileUserIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/apps': typeof AuthenticatedAppsIndexLazyRoute
  '/calendar': typeof AuthenticatedCalendarIndexLazyRoute
  '/challenges': typeof AuthenticatedChallengesIndexLazyRoute
  '/chats': typeof AuthenticatedChatsIndexLazyRoute
  '/createTests': typeof AuthenticatedCreateTestsIndexLazyRoute
  '/dashboard-manager': typeof AuthenticatedDashboardManagerIndexLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/pinboard': typeof AuthenticatedPinboardIndexLazyRoute
  '/settings': typeof AuthenticatedSettingsIndexLazyRoute
  '/tasks': typeof AuthenticatedTasksIndexLazyRoute
  '/testHistory': typeof AuthenticatedTestHistoryIndexLazyRoute
  '/tests': typeof AuthenticatedTestsIndexLazyRoute
  '/users': typeof AuthenticatedUsersIndexLazyRoute
  '/calendar/route/options': typeof AuthenticatedCalendarRouteOptionsRoute
  '/reports/$testId/$collaboratorId': typeof AuthenticatedReportsTestIdCollaboratorIdRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdIndexLazyRoute
  '/courses/$courseId/levels/$levelId': typeof AuthenticatedCoursesCourseIdLevelsLevelIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/RootPage': typeof RootPageRoute
  '/root': typeof RootRoute
  '/(auth)/500': typeof auth500Route
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/jwtdecoder': typeof AuthenticatedJwtdecoderRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-in-2': typeof authSignIn2LazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/collaboratorHistory/$userId': typeof AuthenticatedCollaboratorHistoryUserIdRoute
  '/_authenticated/editTest/$testId': typeof AuthenticatedEditTestTestIdRoute
  '/_authenticated/testInterface/$testId': typeof AuthenticatedTestInterfaceTestIdRoute
  '/_authenticated/userProfile/$userId': typeof AuthenticatedUserProfileUserIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexLazyRoute
  '/_authenticated/calendar/': typeof AuthenticatedCalendarIndexLazyRoute
  '/_authenticated/challenges/': typeof AuthenticatedChallengesIndexLazyRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexLazyRoute
  '/_authenticated/createTests/': typeof AuthenticatedCreateTestsIndexLazyRoute
  '/_authenticated/dashboard-manager/': typeof AuthenticatedDashboardManagerIndexLazyRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/_authenticated/pinboard/': typeof AuthenticatedPinboardIndexLazyRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexLazyRoute
  '/_authenticated/testHistory/': typeof AuthenticatedTestHistoryIndexLazyRoute
  '/_authenticated/tests/': typeof AuthenticatedTestsIndexLazyRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexLazyRoute
  '/_authenticated/calendar/route/options': typeof AuthenticatedCalendarRouteOptionsRoute
  '/_authenticated/reports/$testId/$collaboratorId': typeof AuthenticatedReportsTestIdCollaboratorIdRoute
  '/_authenticated/courses/$courseId/': typeof AuthenticatedCoursesCourseIdIndexLazyRoute
  '/_authenticated/courses/$courseId/levels/$levelId': typeof AuthenticatedCoursesCourseIdLevelsLevelIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/RootPage'
    | '/root'
    | '/500'
    | '/otp'
    | '/sign-in'
    | '/jwtdecoder'
    | '/settings'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/'
    | '/collaboratorHistory/$userId'
    | '/editTest/$testId'
    | '/testInterface/$testId'
    | '/userProfile/$userId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/calendar'
    | '/challenges'
    | '/chats'
    | '/createTests'
    | '/dashboard-manager'
    | '/help-center'
    | '/pinboard'
    | '/settings/'
    | '/tasks'
    | '/testHistory'
    | '/tests'
    | '/users'
    | '/calendar/route/options'
    | '/reports/$testId/$collaboratorId'
    | '/courses/$courseId'
    | '/courses/$courseId/levels/$levelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/RootPage'
    | '/root'
    | '/500'
    | '/otp'
    | '/sign-in'
    | '/jwtdecoder'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/'
    | '/collaboratorHistory/$userId'
    | '/editTest/$testId'
    | '/testInterface/$testId'
    | '/userProfile/$userId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/calendar'
    | '/challenges'
    | '/chats'
    | '/createTests'
    | '/dashboard-manager'
    | '/help-center'
    | '/pinboard'
    | '/settings'
    | '/tasks'
    | '/testHistory'
    | '/tests'
    | '/users'
    | '/calendar/route/options'
    | '/reports/$testId/$collaboratorId'
    | '/courses/$courseId'
    | '/courses/$courseId/levels/$levelId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/RootPage'
    | '/root'
    | '/(auth)/500'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/_authenticated/jwtdecoder'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/collaboratorHistory/$userId'
    | '/_authenticated/editTest/$testId'
    | '/_authenticated/testInterface/$testId'
    | '/_authenticated/userProfile/$userId'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/apps/'
    | '/_authenticated/calendar/'
    | '/_authenticated/challenges/'
    | '/_authenticated/chats/'
    | '/_authenticated/createTests/'
    | '/_authenticated/dashboard-manager/'
    | '/_authenticated/help-center/'
    | '/_authenticated/pinboard/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/testHistory/'
    | '/_authenticated/tests/'
    | '/_authenticated/users/'
    | '/_authenticated/calendar/route/options'
    | '/_authenticated/reports/$testId/$collaboratorId'
    | '/_authenticated/courses/$courseId/'
    | '/_authenticated/courses/$courseId/levels/$levelId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  RootPageRoute: typeof RootPageRoute
  RootRoute: typeof RootRoute
  auth500Route: typeof auth500Route
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignIn2LazyRoute: typeof authSignIn2LazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  RootPageRoute: RootPageRoute,
  RootRoute: RootRoute,
  auth500Route: auth500Route,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignIn2LazyRoute: authSignIn2LazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/RootPage",
        "/root",
        "/(auth)/500",
        "/(auth)/otp",
        "/(auth)/sign-in",
        "/(auth)/forgot-password",
        "/(auth)/sign-in-2",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/jwtdecoder",
        "/_authenticated/settings",
        "/_authenticated/",
        "/_authenticated/collaboratorHistory/$userId",
        "/_authenticated/editTest/$testId",
        "/_authenticated/testInterface/$testId",
        "/_authenticated/userProfile/$userId",
        "/_authenticated/apps/",
        "/_authenticated/calendar/",
        "/_authenticated/challenges/",
        "/_authenticated/chats/",
        "/_authenticated/createTests/",
        "/_authenticated/dashboard-manager/",
        "/_authenticated/help-center/",
        "/_authenticated/pinboard/",
        "/_authenticated/tasks/",
        "/_authenticated/testHistory/",
        "/_authenticated/tests/",
        "/_authenticated/users/",
        "/_authenticated/calendar/route/options",
        "/_authenticated/reports/$testId/$collaboratorId",
        "/_authenticated/courses/$courseId/",
        "/_authenticated/courses/$courseId/levels/$levelId"
      ]
    },
    "/RootPage": {
      "filePath": "RootPage.tsx"
    },
    "/root": {
      "filePath": "root.tsx"
    },
    "/(auth)/500": {
      "filePath": "(auth)/500.tsx"
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/_authenticated/jwtdecoder": {
      "filePath": "_authenticated/jwtdecoder.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/appearance",
        "/_authenticated/settings/display",
        "/_authenticated/settings/notifications",
        "/_authenticated/settings/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.lazy.tsx"
    },
    "/(auth)/sign-in-2": {
      "filePath": "(auth)/sign-in-2.lazy.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.lazy.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.lazy.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/collaboratorHistory/$userId": {
      "filePath": "_authenticated/collaboratorHistory/$userId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/editTest/$testId": {
      "filePath": "_authenticated/editTest/$testId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/testInterface/$testId": {
      "filePath": "_authenticated/testInterface/$testId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/userProfile/$userId": {
      "filePath": "_authenticated/userProfile/$userId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/appearance": {
      "filePath": "_authenticated/settings/appearance.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/display": {
      "filePath": "_authenticated/settings/display.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/notifications": {
      "filePath": "_authenticated/settings/notifications.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/apps/": {
      "filePath": "_authenticated/apps/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/calendar/": {
      "filePath": "_authenticated/calendar/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/challenges/": {
      "filePath": "_authenticated/challenges/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/chats/": {
      "filePath": "_authenticated/chats/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/createTests/": {
      "filePath": "_authenticated/createTests/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard-manager/": {
      "filePath": "_authenticated/dashboard-manager/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/help-center/": {
      "filePath": "_authenticated/help-center/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/pinboard/": {
      "filePath": "_authenticated/pinboard/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/tasks/": {
      "filePath": "_authenticated/tasks/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/testHistory/": {
      "filePath": "_authenticated/testHistory/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/tests/": {
      "filePath": "_authenticated/tests/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/users/": {
      "filePath": "_authenticated/users/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/calendar/route/options": {
      "filePath": "_authenticated/calendar/route.options.ts",
      "parent": "/_authenticated"
    },
    "/_authenticated/reports/$testId/$collaboratorId": {
      "filePath": "_authenticated/reports/$testId/$collaboratorId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/courses/$courseId/": {
      "filePath": "_authenticated/courses/$courseId/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/courses/$courseId/levels/$levelId": {
      "filePath": "_authenticated/courses/$courseId/levels/$levelId.lazy.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
